
apiVersion: v1
kind: Service
metadata:
  name: propexp
  labels:
    app: propexp
    tier: backend
    team: 2phase
spec:
  type: NodePort
  ports:
  - name: svcport
    port: 8080
    nodePort: 31080
    targetPort: 8080
  - name: debug
    port: 4000
    nodePort: 31040
    protocol: TCP
    targetPort: 4000
  selector:
    app: propexp
    tier: backend
    team: 2phase
